---
#
#  setup_jupyterhub.yml
#
container_version: may27
dockerhub_id: phaustin
hub_service_name: e211hub
notebook_service_name: e211book
hub_domain: "jupyter.eoastest2.xyz"
jupyterhub_template_list:
  - { src: "files/docker-compose-jupyterhub.j2"  , dest: "{{ git_remote_path }}/jupyterhub/docker-compose-jupyterhub.yml" }
  - { src: "files/Dockerfile_hub.j2" , dest: "{{ git_remote_path }}/jupyterhub/hub_image/Dockerfile" }
  - { src: "files/Dockerfile_notebook.j2" , dest: "{{ git_remote_path }}/jupyterhub/{{ notebook_service_name }}_image/Dockerfile" }
  - { src: "files/Dockerfile_base.j2" , dest: "{{ git_remote_path }}/jupyterhub/base_image/Dockerfile" }
  - { src: "files/jupyterhub_config.j2" , dest: "{{ git_remote_path }}/jupyterhub/hub_image/jupyterhub_config.py" }



