---
#
#  - jinja2 template variables
#
nbgrader_domain: nbgrader.eoastestb.xyz
nbgrader_forward_auth_service: nbgrader-forward-auth
nbgrader_forward_auth_container_name: nbgrader-forward-auth-container
nbgrader_service: nbgrader
nbgrader_container: nbgrader_container
nbgrader_image: nbgrader_image
nbgrader_exchange_dir: EOSC211_exchange
nbgrader_template_list:
  - { src: "templates/nbgrader/docker-compose-nbgrader-oauth.j2"  , dest: "{{ git_remote_path }}/nbgrader/docker-compose-nbgrader-oauth.yml" }
  - { src: "templates/nbgrader/nbgrader_config.j2"  , dest: "{{ git_remote_path }}/nbgrader/nbgrader_image/nbgrader_config.py" }




