---
#
# setup_traefik.yml
#
#  - jinja2 template variables
#
root_domain: eoastest2.xyz
path_prefix_whoami1: try3
path_prefix_whoami2: try4
network_name: traefik_net
user_and_pw: 'eoas:$2y$05$2N25nFVO13/Xxv4JUetyou5eo2xnrZ5rUHXJF0/P59gwZUGgZUdrC'
#
# - src and dest loop for template
#
traefik_template_list:
  - { src: "files/traefik/docker-compose-proxy.j2" , dest: "{{ git_remote_path }}/docker-compose-proxy.yml" }
  - { src: "files/traefik/traefik.j2" , dest: "{{ git_remote_path }}/traefik/config/traefik.yml" }
  - { src: "files/traefik/middleware.j2" , dest: "{{ git_remote_path }}/traefik/config/dynamic/middleware.yml" }
  - { src: "files/traefik/routers.j2" , dest: "{{ git_remote_path }}/traefik/config/dynamic/routers.yml" }

#
# start_traefik.yml
#
DO_AUTH_TOKEN: "{{ vault_do_auth_token }}"

