---
#
#  - jinja2 template variables
#
book_domain: web.{{ root_domain }}
book_name: a301_book
book_path: ./book_html_source
book_local_source: ${HOME}/repos/
book_prefix: /a301
website_template_list:
  - { src: "templates/website/docker-compose-website.j2"  , dest: "{{ git_remote_path }}/website/docker-compose-website.yml" }



