all:
  children:
    local:
    nxroot:
    nxjov:
    jx:
local:
  hosts:
    127.0.0.1:
  vars:
    ansible_connection: local
nxroot:
  hosts:
    n1x:
      ansible_host: eoas01.eoas.ubc.ca
      ansible_ssh_private_key_file: ~/.ssh/tlef_summer
      remote_user: root
    n3:
    n4:
    n5:
nxjov:
  hosts:
    n1jov:
    n3jov:
    n4jov:
    n5jov:
do:
  hosts:
    do1:
    do1jov:
jx:
  hosts:
    j1:
    j1jov:
    j2:
    j2jov:
dashboards:
  hosts:
    dash:
    dashjov:
