---
- hosts: all
  vars:
    user: 'jovyan'
  remote_user: "{{ user }}"
  pre_tasks:
    - name: Set authorized key taken from file
      vars:
        key_path:
          - '/.ssh/tlef_key1.pub'
          - '/.ssh/tlef_summer.pub'
          - '/.ssh/phil_git.pub'
      ansible.posix.authorized_key:
        user: '{{ user }}'
        state: present
        exclusive: False
        key: "{{ lookup('file', lookup('env','HOME') + item ) }}"
      tags:
        'step1'
      loop: '{{ key_path }}'
  post_tasks:
    - name: conda init bashrc
      shell: |
        /home/jovyan/mini_3_10/condabin/conda init bash
  roles:
    - role: mambaorg.micromamba
      vars: 
        root_prefix: /home/jovyan/mini_3_10
        root_prefix_condarc:
          channels:
            - conda-forge
        packages:
          - mamba
          - python=3.10
          - numpy
          - pandas
          - fsspec


