---
- hosts: all
  become: true
  vars:
    key_path: '/.ssh/tlef_summer.pub'

  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: root
        state: present
        exclusive: True
        key: "{{ lookup('file', lookup('env','HOME') + key_path ) }}"
      tags: step1
