---
- hosts: all
  become: true
  vars:
    key_path:
      - '/.ssh/tlef_key1.pub'
      - '/.ssh/tlef_summer.pub'
    user: 'jovyan'
    packages:
      - mamba
      - python=3.9
      - numpy
      - pandas
  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: '{{ user }}'
        state: present
        exclusive: False
        key: "{{ lookup('file', lookup('env','HOME') + item ) }}"
      tags:
        'step1'
      loop: '{{ key_path }}'
  roles:
    - role: mambaorg.micromamba
      vars: 
        root_prefix: /home/jovyan/mini39
    
    


