FROM {{ dockerhub_id }}/{{ hub_service_name }}:{{ container_version }}

USER ${NB_USER}

RUN mkdir -p ${HOME}/work

COPY jupyter_notebook_config.py /etc/jupyter/

RUN echo "conda activate ${CONDA_ENV}" >> ${HOME}/.bashrc
COPY jupyter_notebook_config.py /etc/jupyter/

WORKDIR "${HOME}/work"

RUN touch "/home/jovyan/container_version_{{ container_version }}.txt"


CMD ["jupyterhub-singleuser"]

