FROM "{{ ocese_base_image }}"

USER ${NB_USER}

RUN mkdir -p ${HOME}/work

COPY jupyter_notebook_config.py /etc/jupyter/

RUN echo "conda activate ${CONDA_ENV}" >> ${HOME}/.bashrc
COPY jupyter_notebook_config.py /etc/jupyter/

WORKDIR "${HOME}/work"

RUN touch "{{ notebook_version_marker }}"

CMD ["jupyterhub-singleuser"]

