version: '3'

services:

  a301_book:
    image: httpd:2.4.51
    container_name: a301_book_image
    volumes:
      - ./book_html_source/html:/usr/local/apache2/htdocs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - "traefik.http.routers.a301_book.rule=Host(`web.eoastest2.xyz`)"
      - traefik.http.routers.a301_book.tls=true
      - traefik.http.routers.a301_book.tls.certresolver=lets-encrypt
      - traefik.http.routers.a301_book.service=a301_book
      - traefik.http.services.a301_book.loadbalancer.server.port=80
      - "traefik.http.routers.a301_book.middlewares=traefik2-forward-auth"
    restart: on-failure
    networks:
      - traefik_net

  traefik2-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    environment:
      - DEFAULT_PROVIDER=generic-oauth
      - INSECURE_COOKIE=false # Example assumes no https, do not use in production
      - PROVIDERS_GENERIC_OAUTH_AUTH_URL=https://github.com/login/oauth/authorize
      - PROVIDERS_GENERIC_OAUTH_TOKEN_URL=https://github.com/login/oauth/access_token
      - PROVIDERS_GENERIC_OAUTH_USER_URL=https://api.github.com/user
      - PROVIDERS_GENERIC_OAUTH_CLIENT_ID
      - PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET
      - AUTH_HOST=auth.eoastest2.xyz:80
      - WHITELIST
      - SECRET
      - USER_ID_PATH=login
    labels:
      - "traefik.http.routers.traefik2-forward-auth.rule=Host(`auth.eoastest2.xyz`)"
      - "traefik.http.routers.traefik2-forward-auth.tls=true"
      - "traefik.http.routers.traefik2-forward-auth.tls.certresolver=lets-encrypt"
      - "traefik.http.middlewares.traefik2-forward-auth.forwardauth.address=http://traefik2-forward-auth:4181"
      - "traefik.http.middlewares.traefik2-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.middlewares.traefik2-forward-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.services.traefik2-forward-auth.loadbalancer.server.port=4181"
      - traefik.enable=true
    networks:
      - traefik_net
    container_name: forward_auth2



networks:
    traefik_net:
      external: true
