name: mainsite
channels:
  - eoas_ubc
  - conda-forge
  - defaults
dependencies:
  - git
  - python=3.9
  - pip
  - pillow
  - bokeh
  - nbgitpuller>1.0
  - jupytext
  - conda-lock
  - jupyterlab
  - jupyterhub=2.3
  - mamba
  - scipy
  - matplotlib
  - numpy
  - pandas
# conda-lock --kind explicit --file environment.yml -p linux-64
