---
- hosts: all
  vars_files:
    - vars/jovyan_vars.yml
    - vars/traefik_vars.yml
    - vars/jupyterhub_vars.yml
  tasks:
    - name: fill and copy templates for jupyterhub
      template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      loop:
        "{{ jupyterhub_template_list }}"
    #https://ahelpme.com/software/ansible/ansible-using-ansible-vault-with-copy-module-to-decrypt-on-the-fly-files/
    - name: decrypt and copy user_list.txt
      copy:
        src: 'files/jupyterhub/vault_user_list.txt'
        dest: '{{ git_remote_path }}/jupyterhub/{{ hub_service_name }}_image/user_list.txt'
        decrypt: yes
        backup: no
        



