---
- hosts: all
  vars_files:
    - vars/jovyan_vars.yml
  pre_tasks:
    - name: copy condarc
      copy:
        src: 'files/conda/condarc.yml'
        dest: '~/.condarc'
  post_tasks:
    - name: conda init bashrc
      shell: |
        {{ conda_prefix }}/condabin/conda init bash
  roles:
    # https://github.com/mamba-org/ansible-role-micromamba
    - role: mambaorg.micromamba
      vars: 
        root_prefix: "{{ conda_prefix }}"
        dest: ~/bin/micromamba
        root_prefix_condarc:
          channels:
            - conda-forge
        packages:
          - mamba
          - python=3.10
          - git
          - gh-scoped-creds


