---
- hosts: all
  vars_files:
    - vars/jovyan_vars.yml
    - vars/traefik_vars.yml
    - vars/nbgrader_vars.yml
    - vars/vault.yml
  tasks:
    - name: create exchange_dir
      file:
        path: "{{ git_remote_path }}/nbgrader/demo/{{ nbgrader_exchange_dir }}"
        state: directory
        mode: '777'
    - name: instantiate templates
      template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      loop:
        "{{ nbgrader_template_list }}"


