---
- hosts: all
  vars_files:
    - vars/jovyan_vars.yml
    - vars/traefik_vars.yml
    - vars/website_vars.yml
  tasks:
    - name: fill and copy templates for website
      template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      loop:
        "{{ website_template_list }}"
    - name: make the html source folder
      file:
        path: "{{ git_remote_path }}/website/{{ book_path }}"
        state: directory
        



