---
- hosts: all
  vars_files:
    - vars/jovyan_vars.yml
    - vars/traefik_vars.yml
    - vars/jupyterhub_vars.yml
  tasks:
    - name: write docker-compose.yml for jupyterhub
      template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      loop:
        "{{ jupyterhub_template_list }}"


