---
- hosts: all
  vars_files:
    - vars/default.yml
    - vars/jupyterhub.yml
  tasks:
    - name: write docker-compose.yml for jupyterhub
      template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      loop:
        "{{ jupyterhub_template_list }}"


