---
- hosts: all
  vars_files:
    - vars/jovyan_vars.yml
    - vars/traefik_vars.yml
    - vars/vault.yml
  tasks:
    - name: move proxy templates to ~/repos/addon_containers
      template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      loop:
        "{{ traefik_template_list }}"


