---
- hosts: all
  vars_files:
    - vars/jovyan_vars.yml
  pre_tasks:
    - name: folder to install micromaba
      file:
        path: "~/bin"
        state: directory
    - name: copy condarc
      copy:
        src: 'files/conda/condarc.yml'
        dest: '~/.condarc'
  post_tasks:
    - name: conda init bashrc
      shell: |
        {{ conda_prefix }}/condabin/conda init bash
  roles:
    # https://github.com/mamba-org/ansible-role-micromamba
    - role: mambaorg.micromamba
      vars: 
        root_prefix: "{{ conda_prefix }}"
        dest: ~/bin/micromamba
        root_prefix_condarc:
          channels:
            - conda-forge
        packages:
          - mamba
          - python=3.11
          - conda-lock
          - git
          - gh-scoped-creds
          
# https://github.com/mamba-org/ansible-role-micromamba
# ansible-playbook -i ~/repos/ubc-jupyter/ansible/hosts.yml -l dash -u jovyan setup_conda.yml 

