---
- hosts: all
  vars_files:
    - vars/default.yml
  tasks:
    - name: move proxy templates to ~/repos/addon_containers
      template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      loop:
        "{{ template_list }}"


