---
- hosts: all
  vars_files:
    # traefik_git_remote_path
    - vars/jovyan_vars.yml
    # vault_do_auth_token
    - vars/vault.yml
  tasks:
    - name: start traefik
      shell: "docker-compose -f docker-compose-noauth.yml up -d"
      environment:
        DO_AUTH_TOKEN: "{{ vault_do_auth_token }}"
        # using traefik-forward-auth
      register: envvar_test
      args:
        chdir: "{{ traefik_git_remote_path }}"
        executable: /bin/bash

    # - name: print envvar result
    #   debug:
    #     msg: "stdout: {{ envvar_test.stdout }}"

