---
- hosts: all
  vars_files:
    - vars/jovyan_vars.yml
    - vars/jupyterhub_vars.yml
    - vars/vault.yml
  tasks:
    - name: start jupyterhub
      shell: "docker-compose -f docker-compose-jupyterhub.yml up -d"
      environment:
        OAUTH_CALLBACK_URL: "{{ OAUTH_CALLBACK_URL }}"
        OAUTH_CLIENT_ID: "{{ GITHUB_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ GITHUB_CLIENT_SECRET }}"
      register: jupyterhub_status
      args:
        chdir: "{{ git_remote_path }}/jupyterhub"
        executable: /bin/bash


