---
- hosts: all
  vars_files:
    - vars/jovyan_vars.yml
    - vars/traefik_vars.yml
    - vars/vault.yml
  tasks:
    - name: start traefik
      shell: "docker-compose -f docker-compose-github-proxy.yml up -d"
      environment:
        DO_AUTH_TOKEN: "{{ vault_do_auth_token }}"
        # using traefik-forward-auth
        PROVIDERS_GENERIC_OAUTH_CLIENT_ID: "{{ vault_traefik_github_client_id }}"
        PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET: "{{ vault_traefik_github_client_secret }}"
        SECRET: "{{ vault_traefik_github_cookie_secret }}"
        WHITELIST: "{{ vault_traefik_github_whitelist }}"
      register: envvar_test
      args:
        chdir: "{{ git_remote_path }}"
        executable: /bin/bash

    # - name: print envvar result
    #   debug:
    #     msg: "stdout: {{ envvar_test.stdout }}"


