---
- hosts: all
  vars:
    root_domain: phaustin.org
    path_prefix_whoami1: try1
    path_prefix_whoami2: try2
    network_name: traefik_net
    user_and_pw: 'eoas:$2y$05$2N25nFVO13/Xxv4JUetyou5eo2xnrZ5rUHXJF0/P59gwZUGgZUdrC'
  tasks:
    #https://stackoverflow.com/questions/67303471/ansible-use-stdout-lines-from-registered-variable-which-uses-loop-in-shell-modu
    - name: test loop
      ansible.builtin.shell: "echo testing_loop_{{ item }}"
      loop:
        - "one"
        - "two"
      register: loop_test
      
    - name: print loop_test result
      debug:
        msg: "stdout_lines: {{ item.stdout_lines }}"
      when: "item.stdout_lines | length > 0"
      loop: "{{ loop_test.results }}"
      
    - name: test dictionary
      ansible.builtin.shell: "echo testing_dict_{{ item.src }}  and  testing_dict__{{ item.dest }} "
      loop:
        - { src: "one" , dest: 'alpha' }
        - { src: "two" , dest: 'beta' }
      register: dict_test

    - name: print dict_test result
      debug:
        msg: "stdout_lines: {{ item.stdout_lines }}"
      when: "item.stdout_lines | length > 0"
      loop: "{{ dict_test.results }}"

    - name: Echo my_env_var
      shell: "echo $MY_ENV_VARIABLE"
      environment:
        MY_ENV_VARIABLE: whatever_value
      register: envvar_test

    - name: print envvar result
      debug:
        msg: "stdout: {{ envvar_test.stdout }}"

